# -*- coding: utf-8 -*-
"""clean_undefined

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ov_DeeiQDezUjeSbkYUeuDdDbmOxjj7t
"""

"""
Run the node-find-undefined program with the js file and output the result to a txt file:

  ./node-find-undefined filename.js > resultfile.txt

Then, run the following:

  python3 clean_undefined.py path_to_resultfile.txt

Need to specify the resultfile.txt path.

The command line will print out the undefined properties in array format.
"""
import re;
import os;
import sys;
import json;

undefined = []
undefined_no_repeat = []



def get_undefined(line):
  if "KeyName::" in line:
    index = line.find("#")
    if index != -1:
      name = line[index + 1:]
      undefined.append(name.strip())

    ## keyed property like index 0x3 for array
    ## jackfromeast
    match = re.search(r"\((\d+)\)", line)
    if match:
      key_name = match.group(1)
      undefined.append(key_name.strip("()").strip())


def main():
  args = sys.argv[1:]
  path = args[0]

  f = open(path, 'r')

  need = False
  for line in f:
      get_undefined(line)

  undefined_no_repeat = list(set(undefined))

  ## remove known undefined properties
  for key in IgnoreUndefProps:
      for prop in IgnoreUndefProps[key]:
        if prop in undefined_no_repeat:
          undefined_no_repeat.remove(prop)


  # generate json format array for undefined properties
  undefined_no_repeat_json = json.dumps(undefined_no_repeat)
  print(undefined_no_repeat_json)

if __name__ == '__main__':
  main()


