# -*- coding: utf-8 -*-
"""clean_undefined

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ov_DeeiQDezUjeSbkYUeuDdDbmOxjj7t
"""

"""
How to use this:
Before running the node-find-undefined program, add:

  console.log("===========start")
  console.log("===========end")

At the beginning and end of the js file respectively.

Then, run the node-find-undefined program with the js file and output the result to a txt file:

  ./node-find-undefined filename.js > resultfile.txt

Then, run the following:

  python3 clean_undefined.py path_to_resultfile.txt

Need to specify the resultfile.txt path.

The command line will print out the undefined properties in array format.
"""

import os;
import sys;

undefined = []
undefined_no_repeat = []

def get_undefined(line):
  if "KeyName::" in line:
    index = line.find("#")
    if index != -1:
      name = line[index + 1:]
      undefined.append(name.strip())

def main():
  args = sys.argv[1:]
  path = args[0]

  f = open(path, 'r')

  need = False
  for line in f:
    if line == "===========start\n":
      need = True
      continue
    elif line == "===========end\n":
      need = False
      continue
    elif need:
      get_undefined(line)

  undefined_no_repeat = list(set(undefined))
  print(undefined_no_repeat)

if __name__ == '__main__':
  main()


