# -*- coding: utf-8 -*-
"""clean_undefined

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ov_DeeiQDezUjeSbkYUeuDdDbmOxjj7t
"""

"""
How to use this:
Before running the node-find-undefined program, add:

  console.log("===========start")
  console.log("===========end")

At the beginning and end of the js file respectively.

Then, run the node-find-undefined program with the js file and output the result to a txt file:

  ./node-find-undefined filename.js > resultfile.txt

Then, run the following:

  python3 clean_undefined.py path_to_resultfile.txt path_to_outputfile.txt

Need to specify the resultfile.txt path and the output file path.

The result file contains undefined property name with "\n" as separation.
At the same time, the command line will print out the undefined properties in array format.
"""

import os;
import sys;

undefined = []

def get_undefined(line):
  if "KeyName::" in line:
    index = line.find("#")
    name = line[index + 1:]
    undefined.append(name.strip())

def write_output(file_name):
  with open(file_name, 'w') as txt_file:
    for name in undefined:
      txt_file.write(name + "\n")

def main():
  args = sys.argv[1:]
  path = args[0]
  output = args[1]

  f = open(path, 'r')

  need = False
  for line in f:
    if line == "===========start\n":
      need = True
      continue
    elif line == "===========end\n":
      need = False
      continue
    elif need:
      get_undefined(line)

  print(undefined)
  write_output(output)

if __name__ == '__main__':
  main()


